In [1]:
import numpy as np

In [3]:
print(np.__version__)

1.26.4


In [5]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
# Array
#1D
#2D
#3D

In [5]:
import numpy as np
a1 = np.array([2,4,6]) # 1Dimention Array

In [7]:
print(a1)

[2 4 6]


In [9]:
a2 = np.array([[2,4,6],[3.5,6.5,7.9]]) # 2Diemention Array

In [11]:
print(a2)

[[2.  4.  6. ]
 [3.5 6.5 7.9]]


In [31]:
a3 = np.array([[[2,4,6],[3,5.2,7.7],[8,9,0]],[[10,11,12],[13,14,15],[16,17,18]]]) # 3 Diemention Array

In [33]:
print(a3)

[[[ 2.   4.   6. ]
  [ 3.   5.2  7.7]
  [ 8.   9.   0. ]]

 [[10.  11.  12. ]
  [13.  14.  15. ]
  [16.  17.  18. ]]]


In [35]:
a2.shape

(2, 3)

In [37]:
a1.shape

(3,)

In [39]:
a3.shape

(2, 3, 3)

In [41]:
a2.size

6

In [43]:
a3.size

18

In [45]:
type(a3)

numpy.ndarray

In [47]:
data_array = np.array([2,4,6])

In [49]:
data_array

array([2, 4, 6])

In [51]:
data_array.dtype

dtype('int32')

In [53]:
data_ones = np.ones((2,2))

In [55]:
print(data_ones)

[[1. 1.]
 [1. 1.]]


In [59]:
data_ones = np.ones((6,6))

In [61]:
print(data_ones)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [63]:
data_ones.dtype

dtype('float64')

In [65]:
data_ones.astype(int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [67]:
data_zeros = np.zeros((5,3,3))
print(data_zeros)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [69]:
range_array = np.arange(1,12,2)
print(range_array)

[ 1  3  5  7  9 11]


In [71]:
random_data = np.random.randint(10, size = (5,3))
print(random_data)

[[8 7 0]
 [9 2 3]
 [5 2 3]
 [9 2 7]
 [0 2 7]]


In [73]:
np.random.random((5,3))

array([[0.26331825, 0.74012406, 0.59759956],
       [0.93945633, 0.69073266, 0.66688209],
       [0.67800668, 0.39265927, 0.62290539],
       [0.63837689, 0.14380781, 0.5411854 ],
       [0.00293933, 0.66551143, 0.85448631]])

In [75]:
np.random.rand(5,3)

array([[0.63798579, 0.25234753, 0.05946342],
       [0.8964248 , 0.18700576, 0.40555103],
       [0.41029708, 0.06757886, 0.12050084],
       [0.41343391, 0.07783025, 0.84742   ],
       [0.38217941, 0.43250764, 0.24027159]])

In [1]:
#Resapingnof array
#Arithmatic operation
#manipulation of Array
#Conditional Operators

In [3]:
#ravel()
#flatten()
#squeeze()

In [5]:
import numpy as np
a4 = np.random.randint(10, size = (2,3,4,5))
print(a4)

[[[[4 2 6 2 6]
   [2 3 0 9 0]
   [0 9 0 6 8]
   [0 1 1 8 2]]

  [[2 2 7 0 3]
   [7 9 3 3 8]
   [2 0 7 7 7]
   [6 1 4 3 2]]

  [[0 2 0 7 9]
   [3 5 3 5 8]
   [5 1 0 3 5]
   [7 8 9 4 1]]]


 [[[8 8 2 2 5]
   [4 1 7 4 5]
   [2 2 4 8 2]
   [4 4 0 4 4]]

  [[1 5 4 3 8]
   [1 3 4 0 2]
   [6 9 9 8 2]
   [7 1 4 3 1]]

  [[3 5 8 1 1]
   [7 7 7 0 9]
   [2 4 0 9 8]
   [7 0 5 0 6]]]]


In [7]:
a4.shape

(2, 3, 4, 5)

In [11]:
a4[:, :, :,:4]

array([[[[4, 2, 6, 2],
         [2, 3, 0, 9],
         [0, 9, 0, 6],
         [0, 1, 1, 8]],

        [[2, 2, 7, 0],
         [7, 9, 3, 3],
         [2, 0, 7, 7],
         [6, 1, 4, 3]],

        [[0, 2, 0, 7],
         [3, 5, 3, 5],
         [5, 1, 0, 3],
         [7, 8, 9, 4]]],


       [[[8, 8, 2, 2],
         [4, 1, 7, 4],
         [2, 2, 4, 8],
         [4, 4, 0, 4]],

        [[1, 5, 4, 3],
         [1, 3, 4, 0],
         [6, 9, 9, 8],
         [7, 1, 4, 3]],

        [[3, 5, 8, 1],
         [7, 7, 7, 0],
         [2, 4, 0, 9],
         [7, 0, 5, 0]]]])

In [13]:
#Arithmatic Operator :
#+,-,*,/,%,**,//
#comparison Operator :
#>,<,>=,<=, ==,!=

In [15]:
#np.exp()
#np.log()
#np.dot() : dot product
#Brodcasting

In [21]:
#aggrigation Function
##np.max()
#np.min()
#np.std()
#np.var()
#np.var()
#np.mean()

In [23]:
a1= np.array([1,2,3])
print(a1)

[1 2 3]


In [25]:
ones = np.ones(3)
print(ones)

[1. 1. 1.]


In [27]:
a1 + ones

array([2., 3., 4.])

In [29]:
a1 - ones


array([0., 1., 2.])

In [31]:
a1 * ones

array([1., 2., 3.])

In [33]:
a1 / ones

array([1., 2., 3.])

In [35]:
a1 ** ones

array([1., 2., 3.])

In [37]:
a1 % ones

array([0., 0., 0.])

In [39]:
a1 // ones

array([1., 2., 3.])

In [41]:
a2 = np.array([2,3,4])
print(a1)
print(a2)

[1 2 3]
[2 3 4]


In [43]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [45]:
sum(a1)

6

In [47]:
sum(a2)

9

In [49]:
import random

In [53]:
data_list = [random.randint(0,10) for i in range(100)]
len(data_list)

100

In [55]:
data_list[: 10]

[3, 0, 7, 7, 9, 1, 2, 6, 4, 7]

In [57]:
np.random.seed(0)

In [76]:
mat1 = np.random.randint(10, size= (3,3))
print(mat1)

[[5 9 4]
 [4 6 4]
 [4 3 4]]


In [78]:
mat2 = np.random.randint(10, size = (3,2))
print(mat2)

[[4 8]
 [4 3]
 [7 5]]


In [80]:
mat1.shape

(3, 3)

In [82]:
mat2.shape

(3, 2)

In [96]:
np.dot(mat1, mat2)

array([[84, 87],
       [68, 70],
       [56, 61]])

In [86]:
mat1

array([[5, 9, 4],
       [4, 6, 4],
       [4, 3, 4]])

In [94]:
mat1 > 2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [1]:
import numpy as np

In [3]:
arr = np.array([10,20,30,40,50,60])

In [5]:
print(arr)

[10 20 30 40 50 60]


In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [9]:
print(arr[1:4])

[20 30 40]


In [11]:
arr = np.array([10,20,30,40,50,60])

In [15]:
arr[:3]

array([10, 20, 30])

In [25]:
arr[:1]

array([10])

In [27]:
arr[3:]

array([40, 50, 60])

In [33]:
print(arr[-2:])

[50 60]


In [55]:
arr2 = np.random.randint(10, size = (1,3,3))
print(arr2)

[[[8 9 6]
  [1 1 1]
  [3 0 8]]]


In [57]:
print(arr2[0:2, 1:])

[[[1 1 1]
  [3 0 8]]]


In [59]:
print(arr2[0:2, 1:])

[[[1 1 1]
  [3 0 8]]]


In [3]:
import numpy as np
arr2 = np.random.randint(10, size = (1,3,3))
print(arr2)


[[[4 9 9]
  [4 5 3]
  [7 1 9]]]


In [5]:
print(arr2[:,0])

[[4 9 9]]


In [7]:
print(arr2[-1, :])

[[4 9 9]
 [4 5 3]
 [7 1 9]]


In [9]:
print(arr2[-1,:-1])

[[4 9 9]
 [4 5 3]]


In [11]:
print(arr2)

[[[4 9 9]
  [4 5 3]
  [7 1 9]]]


In [13]:
print(arr2[-1,:-1])

[[4 9 9]
 [4 5 3]]


In [49]:
arr = np.array([10,20,30,40,50,60])

In [37]:
#np.where : Return chosen from x and y depending on condition.

In [55]:
indices = np.where(arr > 20)

In [57]:
print(indices)

(array([2, 3, 4, 5], dtype=int64),)


In [59]:
arr = np.array([5,10,15,20,25])

In [61]:
even_indices = np.where(arr % 2 == 0)

In [63]:
print(even_indices)

(array([1, 3], dtype=int64),)


In [131]:
np.random.seed(42) # if we put a value in seed then it wil not change the numbers.
#if we put not any value in seed then it will change the whole value.

In [133]:
arr1 = np.random.randint(10,100, size = 10)

In [135]:
print(arr1)

[61 24 81 70 30 92 96 84 84 97]


In [1]:
import numpy as np

In [3]:
a = np.array([0,1,2])
b = np.array([3,4,5])

In [5]:
a+b

array([3, 5, 7])

In [7]:
a*b

array([ 0,  4, 10])

In [9]:
a/b

array([0.  , 0.25, 0.4 ])

In [11]:
import numpy as np

In [13]:
a = np.atleast_1d(5)
print(a.shape)

(1,)


In [15]:
a = np.atleast_1d(a)
print(a.shape)

(1,)


In [17]:
a = np.atleast_2d(a)
print(a.shape)

(1, 1)


In [19]:
a = np.atleast_3d(a)
print(a.shape)

(1, 1, 1)


In [23]:
a = np.atleast_1d(np.zeros((2,3)))
print(a.shape)

(2, 3)


In [25]:
a = np.atleast_2d(a)

In [27]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
print(a.shape)

(2, 3)


In [31]:
a = np.atleast_3d(a)
print(a.shape)

(2, 3, 1)


In [35]:
a = np.arange(0,3)
print(a)

[0 1 2]


In [37]:
a.shape

(3,)

In [39]:
print(a)

[0 1 2]


In [41]:
b = np.broadcast_to(a, (3,3))
print(b.shape)

(3, 3)


In [43]:
print(b)

[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [45]:
import numpy as np

In [47]:
a = np.arange(0,3).reshape(3,1)
b = np.arange(0,5).reshape(1,5)
print(a.shape)
print(b.shape)

(3, 1)
(1, 5)


In [49]:
c , d = np.broadcast_arrays(a, b)

print(c.shape)
print(d.shape)

(3, 5)
(3, 5)


In [51]:
print(c)

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]]


In [53]:
print(d)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [57]:
a = np.arange(0,3).reshape(3,1)
b = np.arange(0,5).reshape(1,5)
print(a.shape)
print(b.shape)

(3, 1)
(1, 5)


In [59]:
new_shape = np.broadcast_shapes(a.shape, b.shape)
print(new_shape)

(3, 5)


In [61]:
new_shapes = np.broadcast_shapes((3,1),(1,5))
print(new_shapes)

(3, 5)
