In [1]:
#Exercise 1: Import numpy as np and see the version.

In [9]:
import numpy as np

In [11]:
print(np.__version__)

1.26.4


In [1]:
# Exercise 2. How to create a 1D array?
import numpy as np
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [11]:
# Exercise 3. How to create a boolean array?

np.ones((3,3), dtype=bool)


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [13]:
# Exercise 4. How to extract items that satisfy a given condition from 1D array?

arr = np.arange(10)

arr[arr%2 == 1]

array([1, 3, 5, 7, 9])

In [15]:
# Exercise 5. How to replace items that satisfy a condition with another value in numpy array?
arr = np.arange(10)

arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [17]:
# Exercise 6. How to replace items that satisfy a condition without affecting the original array?

arr = np.arange(10)

res = arr.copy()

res[res%2 == 1] = -1

print('Modified Array')
print(res)

print('\nOriginal Array')
print(arr)

Modified Array
[ 0 -1  2 -1  4 -1  6 -1  8 -1]

Original Array
[0 1 2 3 4 5 6 7 8 9]


In [25]:
#Exercise 7. How to reshape an array?

arr = np.arange(20)
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [27]:
# Exercise 8. How to stack two arrays vertically?

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [31]:
# Exercise 9. How to stack two arrays horizontally?

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [33]:
# Exercise 10. How to generate custom sequences in numpy without hardcoding?

a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [37]:
# Exercise 11. How to get the common items between two python numpy arrays?
a = np.array([1,2,3,4,5])
b = np.array([3,5,6,7,8])
np.intersect1d(a,b)

array([3, 5])

In [39]:
# Exercise 12. How to remove from one array those items that exist in another?

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [43]:
# Exercise 13. How to get the positions where elements of two arrays match?

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where( a == b)

(array([1, 3, 5, 7], dtype=int64),)

In [45]:
# Exercise 14. How to extract all numbers between a given range from a numpy array?

a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

In [51]:
# Exercise 15. How to make a python function that handles scalars to work on numpy arrays?



In [55]:
# Exercise 16. How to swap two columns in a 2d numpy array?

arr = np.arange(9).reshape(3,3)

arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [73]:
# Exercise 17. How to swap two rows in a 2d numpy array?
arr = np.arange(9).reshape(3,3)
print('Original array')
print(arr)

# Solution

print("\n Swap two Row array")
arr[[1,0,2], :]

Original array
[[0 1 2]
 [3 4 5]
 [6 7 8]]

 Swap two Row array


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [69]:
# Exercise 18. How to reverse the rows of a 2D array?

arr = np.arange(9).reshape(3,3)

print('Original array')
print(arr)

print("\nReversed Row array")
arr[::-1, :]

Original array
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Reversed Row array


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [71]:
# Exercise 19. How to reverse the columns of a 2D array?
arr = np.arange(9).reshape(3,3)
print('Original array')
arr


print("\nReversed column array")
arr[:, ::-1]

Original array

Reversed column array


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [77]:
# Exercise 20. How to create a 2D array containing random floats between 5 and 10?

arr1 = np.random.uniform(5,10, size=(5,3))
arr1

array([[7.87282136, 8.2888625 , 5.09303337],
       [9.46709766, 6.38376506, 8.99975766],
       [9.25292219, 6.21991054, 5.8293006 ],
       [6.7204927 , 7.54640622, 8.60318594],
       [9.35598689, 8.47292499, 5.91732703]])

In [79]:
# Exercise 21. How to print only 3 decimal places in python numpy array?

deci_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
deci_arr

array([[0.722, 0.752, 0.092],
       [0.33 , 0.348, 0.778],
       [0.699, 0.983, 0.467],
       [0.629, 0.458, 0.117],
       [0.687, 0.081, 0.99 ]])

In [97]:
# Exercise 22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

np.random.seed(100)
arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=False)
print(arr)


np.set_printoptions(suppress=True)
arr

[[5.434e-04 2.784e-04 4.245e-04]
 [8.448e-04 4.719e-06 1.216e-04]
 [6.707e-04 8.259e-04 1.367e-04]]


array([[0.001, 0.   , 0.   ],
       [0.001, 0.   , 0.   ],
       [0.001, 0.001, 0.   ]])

In [99]:
# Exercise 23. How to limit the number of items printed in output of numpy array?

a = np.arange(15)
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [101]:
# Exercise 24. How to print the full numpy array without truncating

a = np.arange(15)


np.set_printoptions(threshold=15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
# Exercise 25. How to import a dataset with numbers and texts keeping the text intact in python numpy?

import numpy as np

data = np.genfromtxt("mydata.csv", dtype = None, delimiter= ',',  encoding ='utf-8' )
data

array([['\ufeffId', 'Name', 'Age', 'Salary', 'Department'],
       ['1', 'Dimple', '33', '35000', 'DA'],
       ['2', 'Sejal', '30', '25000', 'AI'],
       ['3', 'Ketan', '35', '45000', 'ML'],
       ['4', 'Ram', '26', '30000', 'DA'],
       ['5', 'Raj', '31', '26000', 'ML'],
       ['6', 'Kavan', '27', '50000', 'DA'],
       ['7', 'Ronak', '35', '40000', 'ML'],
       ['8', 'Vasu', '30', '30000', 'AI'],
       ['9', 'Kunj', '25', '25000', 'ML'],
       ['10', 'Bhargav', '24', '30000', 'DA']], dtype='<U10')

In [35]:
# Exercise 26. How to extract a particular column from 1D array of tuples?

arr = np.array([(5.2, 6.5, 8.10), (56.47, 33.58, 22.14),(5.25, 6.16, 7.7), (7.37, 28.8, 8.9)])
arr[:, 2]


array([ 8.1 , 22.14,  7.7 ,  8.9 ])

In [39]:
# Exercise 27. How to convert a 1d array of tuples to a 2d numpy array?

arr = np.array([(3,5,7),(6,8,9),(2,4,8)])
arr1 = np.vstack(arr)
print(arr1)

[[3 5 7]
 [6 8 9]
 [2 4 8]]


In [57]:
# Exercise 28. How to compute the mean, median, standard deviation of a numpy array?

# Original array 
array = np.arange(10) 
print("Original Array :",array) 
  
arr1 = np.mean(array) 
print("\nMean: ",arr1) 

arr2 = np.median(array)
print("\nMedian: ",arr2)

arr3 = np.std(array) 
print("\nstd: ",arr3) 

arr4 = np.var(array) 
print("\nvariance: ", arr4) 

Original Array : [0 1 2 3 4 5 6 7 8 9]

Mean:  4.5

Median:  4.5

std:  2.8722813232690143

variance:  8.25


In [59]:
# Exercise 29. How to normalize an array so the values range exactly between 0 and 1?

#define array with some values
arr = np.array([10, 4, 5, 6, 2, 8, 11, 20])

# Find the minimum and maximum values in the array
min_arr = np.min(arr)
max_arr = np.max(arr)

# Perform min-max normalization
normalized_arr = (arr - min_arr) / (max_arr - min_arr)
print("\nNormalized Array:",normalized_arr)


Normalized Array: [0.44444444 0.11111111 0.16666667 0.22222222 0.         0.33333333
 0.5        1.        ]


In [ ]:
# Exercise 30. How to compute the softmax score?

